### PR TITLE
Fix Deprecating API authentication through query parameters

### LINKED ISSUE #489: Can no longer login due to deprecating through query param
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: macOS Catalina 10.15.7
* App Version: 1.9.1

#### Description of the problem / feature request / question:
I can no longer log in to Github gist with Lepton. 

#### If possible, provide a sample gist or screenshot:
Looks like Gihub no longer accepts query parameter authentication. Only header-based. From the log: 

- ERROR message: `Must specify access token via Authorization header.`
- ERROR message line [https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) Looks like May 5 is the first brownout scheduled. (See link)

Screen Shot 2021-05-05 at 10 31 09 AM

#### If possible, provide the log files
[2021-05-05T17.14.14.608Z.log](https://github.com/hackjutsu/Lepton/files/6429088/2021-05-05T17.14.14.608Z.log)

### PR DESCRIPTION
**Pull request by EdZava**
As soon as the pull request was created, the problem was fixed by @sunnysidesounds

fixed #489

### CODE REVIEW

**Comment by EdZava** [comment]
@hackjutsu  Can you check the pull request?
This fixes an issue that prevents me and many other people from continuing to use the app.

**Comment by EdZava** [comment]
This project is no longer maintained? 
Please make it clear if this project is dead?

**Comment by hackjutsu** [comment]
Sorry, got distracted by other projects. Just released v1.9.2 with the fix.

**Comment by EdZava** [comment]
Thank you!
Also updated the brew cask of lepton.
https://github.com/Homebrew/homebrew-cask/pull/106863#issuecomment-855927241

**Comment by hackjutsu** [comment]
@all-contributors please add @EdZava for code

**Comment by hackjutsu** [comment]
@all-contributors please add @sunnysidesounds for code

**Pull request merged**
