### PR TITLE
Adopt 3rd editor: CodeMirror

### PR DESCRIPTION
**Pull request by wujysh**
#73 

- [x] resolve tab inserting issue #53 #66
- [x] markdown highlighting
- [x] editor style initial

### CODE REVIEW

**Comment by wujysh** [comment]
#73

**Comment by hackjutsu** [comment]
It looks great! What's the complexity for adding the following features?

- language highlighting according to filename
- editor theme setting (use the [github-gist style](https://github.com/hackjutsu/Lepton/blob/master/app/utilities/vendor/highlightJS/styles/github-gist.css)?)

If that takes time, I can merge this PR now and put those feature later.

**Comment by hackjutsu** [comment]
You can rebase or squash your commits before sending the PR, so that we won't have the commit like "revert unnecessary changes".

**Comment by wujysh** [comment]
@hackjutsu I will rebase later.
We should decide which addons should be used from CodeMirror. There are too many thing can be modified..
p.s. Is there any better way to include these CodeMirror libraries? (Webpack problem?)

**Comment by hackjutsu** [comment]
@wujysh 

Maybe we should keep CodeMirror addons as a separate feature issue. 

IMHO, 1st, 2nd and 4th commits are sufficient to close https://github.com/hackjutsu/Lepton/issues/53 and https://github.com/hackjutsu/Lepton/issues/66.

**Comment by wujysh** [comment]
@hackjutsu OK. I will clean up the commits for you to merge.

**Comment by wujysh** [comment]
@hackjutsu Please review.

**Comment by hackjutsu** [comment]
Thanks!

**Pull request merged**
