### PR TITLE
Optional profile photo

### PR DESCRIPTION
**Pull request by baybatu**
Makes profile photo display configurable. Default is `false` that means protect previous behaviour.

### CODE REVIEW

**Comment by baybatu** [comment]
It just provides an option to hide profile photo if user want.

GIF: opt

I clicked on sync button a couple of times after started.

**Comment by hackjutsu** [comment]
Maybe we need a way to show the login username if the profile photo is hidden, but it's good enough for now. Thanks @baybatu !

**Comment by baybatu** [comment]
Thanks @hackjutsu ! Maybe we can use app title (now it is just `Lepton`) for the username. Like in `baybatu@Lepton` or `hackjutsu | Lepton` format.

**Comment by hackjutsu** [comment]
@Calinou Good ideas 👍

**Pull request merged**
