### PR TITLE
add Minimize to disk

### PR DESCRIPTION
**Pull request by npmrun**
i want to add a feature。

### CODE REVIEW

**Comment by hackjutsu** [comment]
@npmrun Sorry for the late reply. Could you attach a screenshot of the new flow?

**Comment by Ugenx** [comment]
Dang, was just looking for this feature and here it is albeit stuck at the finish line it seems? @hackjutsu is the only blocker here that we need a working demo of the feature?

**Comment by hackjutsu** [comment]
It would be great to gain a better understanding of the purpose of new PRs.

**Comment by npmrun** [comment]
sorry about this. I forgot this pr. Here I add some screenshots.
if you click the close button, there will open a dialog
image
if choose Minimize to disk, it will minimizi, just like this: 
image

**Comment by npmrun** [comment]
Actually, I only tested it on my computer, My operating system is win10, I can't guarantee compatibility. This is my firse pr.  ==

**Comment by hackjutsu** [comment]
Thanks, I'll take a look this week.

**Pull request merged**
