### PR TITLE
Support for Apple Silicon

### PR DESCRIPTION
**Pull request by sxyazi**

### CODE REVIEW

**Comment by hackjutsu** [comment]
Thanks for the PR! @sxyazi Can you help clarify the changes? Thanks!

**Comment by sxyazi** [comment]
@hackjutsu Now, for macOS systems, there is a new build option for the arm64 architecture.

**Comment by hackjutsu** [comment]
Thanks!

**Comment by hackjutsu** [comment]
@all-contributors please add @sxyazi for platform

**Pull request merged**
