### PR TITLE
Dark mode for Lepton

### PR DESCRIPTION
**Pull request by hackjutsu**
The implementation is based on @DNLHC 's theme manager. https://github.com/hackjutsu/Lepton/issues/206

Add a new config field `theme` in `~/.leptonrc`. Two supported values, "light" and "dark". "light" is the default value.
```json
{
  "theme": "dark"
}
```

Screen Shot 2019-05-03 at 10 55 41 PM
Screen Shot 2019-05-03 at 10 58 31 PM
Screen Shot 2019-05-03 at 10 59 49 PM
Screen Shot 2019-05-03 at 11 00 53 PM
Screen Shot 2019-05-03 at 11 03 35 PM

### CODE REVIEW

**Comment by WrongGuy** [comment]
I'm a new user, I placed the file
C:\Users\NAME\AppData\Local\Programs\Lepton\ .leptonrc
I changed the code inside this file to
{
"theme": "dark"
}
But when I start Lepton, the dark mode doesn't appear to take effect. I'm using 1.8.0
Can you please guide me what to do further? Am I missing something?

**Comment by hackjutsu** [comment]
Hi @WrongGuy , you might want to put this file in your home directory. https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b

**Comment by zlyin** [comment]
Hi there, I downloaded the .leptonrc file and put it in Linux Home directory. When I change the theme and default_private keyword, it doesn't make a difference. How should I activate those new features?

**Comment by zlyin** [comment]
@hackjutsu Also, I set the default indent as 4, but when I hit tab, it seems only give 2, how to fix it?

**Comment by hackjutsu** [comment]
@zlyin Would you mind creating a new issue? Thanks.

**Comment by imHowie** [comment]
我是Mac OS的用户，我看到你并没有说明Mac如何切换至Dark主题，经过查找，发现你在Template for .leptonrc（https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b）只说明来Liunx和windows上的教程，并没有Mac OS

**Comment by imHowie** [comment]
I am a Mac OS user, I saw that you did not explain how the Mac switched to the Dark theme. After searching, you found that you are only in the Template for .leptonrc (https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b) to Liunx.
And tutorials on windows, and no Mac OS

**Comment by takeTrace** [comment]
> I am a Mac OS user, I saw that you did not explain how the Mac switched to the Dark theme. After searching, you found that you are only in the Template for .leptonrc ([gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b](https://gist.github.com/hackjutsu/1ad7e4968eb64d881ec9dedd6c0f400b)) to Liunx.
> And tutorials on windows, and no Mac OS

you can refrence linux setting

**Pull request merged**
